{"uuid":"908b49c5-f776-4414-a8c8-dc645570113d","historyId":"f4cb85d14778dae3573351c1ef4841aa","fullName":"org.ecommerce.AndroidBaseTest.ConfigureAppium","labels":[{"name":"package","value":"DataProviderFirst.DataProvider1st"},{"name":"testClass","value":"DataProviderFirst.DataProvider1st"},{"name":"testMethod","value":"ConfigureAppium"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"DataProviderFirst.DataProvider1st"},{"name":"host","value":"Anish"},{"name":"thread","value":"667652@Anish.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"AS_ID","value":"-1"}],"links":[],"name":"ConfigureAppium","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"[The local appium server has not been started, Reason: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20015 ms, Consider increasing the server startup timeout value (currently 20000ms), Node.js executable path: C:\\Program Files\\nodejs\\node.exe, Arguments: [C:\\Users\\Anishkumar\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1], Output: \u001B[38;5;112m[Appium]\u001B[0m Welcome to Appium v2.19.0\r\n\u001B[38;5;112m[Appium]\u001B[0m Non-default server args:\r\n\u001B[38;5;112m[Appium]\u001B[0m { address: \u001B[32m'127.0.0.1'\u001B[39m }\r\n\u001B[38;5;112m[Appium]\u001B[0m The autodetected Appium home path: C:\\Users\\Anishkumar\r\n\u001B[38;5;112m[Appium]\u001B[0m Attempting to load driver uiautomator2...\r\n\u001B[38;5;112m[Appium]\u001B[0m Requiring driver at C:\\Users\\Anishkumar\\node_modules\\appium-uiautomator2-driver\\build\\index.js\r\n\u001B[38;5;112m[Appium]\u001B[0m AndroidUiautomator2Driver has been successfully loaded in 1.238s\r\n\u001B[38;5;86m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001B[38;5;112m[Appium]\u001B[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n\u001B[38;5;112m[Appium]\u001B[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at node:net:2203:7\n    at processTicksAndRejections (node:internal/process/task_queues:90:21)\r\n]","trace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: [The local appium server has not been started, Reason: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20015 ms, Consider increasing the server startup timeout value (currently 20000ms), Node.js executable path: C:\\Program Files\\nodejs\\node.exe, Arguments: [C:\\Users\\Anishkumar\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1], Output: \u001B[38;5;112m[Appium]\u001B[0m Welcome to Appium v2.19.0\r\n\u001B[38;5;112m[Appium]\u001B[0m Non-default server args:\r\n\u001B[38;5;112m[Appium]\u001B[0m { address: \u001B[32m'127.0.0.1'\u001B[39m }\r\n\u001B[38;5;112m[Appium]\u001B[0m The autodetected Appium home path: C:\\Users\\Anishkumar\r\n\u001B[38;5;112m[Appium]\u001B[0m Attempting to load driver uiautomator2...\r\n\u001B[38;5;112m[Appium]\u001B[0m Requiring driver at C:\\Users\\Anishkumar\\node_modules\\appium-uiautomator2-driver\\build\\index.js\r\n\u001B[38;5;112m[Appium]\u001B[0m AndroidUiautomator2Driver has been successfully loaded in 1.238s\r\n\u001B[38;5;86m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001B[38;5;112m[Appium]\u001B[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n\u001B[38;5;112m[Appium]\u001B[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at node:net:2203:7\n    at processTicksAndRejections (node:internal/process/task_queues:90:21)\r\n]\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:203)\r\n\tat org.ecommerce.AndroidBaseTest.ConfigureAppium(AndroidBaseTest.java:34)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n\tat org.testng.TestRunner.run(TestRunner.java:621)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\r\n\tat org.testng.TestNG.run(TestNG.java:1082)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\nCaused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20015 ms\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:94)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:157)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:182)\r\n\t... 27 more\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:91)\r\n\t... 29 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1758452106017,"stop":1758452106021}